"use client";

// import type { Metadata } from "next";
import { Jersey_15, Playwrite_AU_SA } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import { useEffect } from "react";

// Load your fonts
const jersey15 = Jersey_15({
  variable: "--font-jersey-15",
  weight: "400",
  subsets: ["latin"],
});

const playwriteAuSa = Playwrite_AU_SA({
  variable: "--font-playwrite-au-sa",
  weight: "400",

});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  useEffect(() => {
    if (typeof document !== "undefined") {
      const pageId = pathname === "/" ? "home" : pathname.split('/').join('');
      document.documentElement.id = pageId;
    }
  }, [pathname]);

  return (
    <html lang="en" className={`${jersey15.variable} ${playwriteAuSa.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}